module.exports = {
  presets: ['module:@react-native/babel-preset'],
  plugins: [
    [
      'module:react-native-dotenv',
      {
        envName: 'APP_ENV',
        moduleName: '@env',
        path: '.env',
        blocklist: null,
        allowlist: null,
        safe: false,
        allowUndefined: false,
        verbose: false,
      },
    ],
    [
      'module-resolver',
      {
        alias: {
          '@src': './src',
          '@assets': './src/assets',
          '@components': './src/components/',
          '@screens': './src/screens/',
          '@utils': './src/utils/',
          '@hooks': './src/hooks/',
          '@constants': './src/constants/',
          '@services': './src/services/',
          '@store': './src/store/',
          '@validations': './src/validations/',
          '@types': './src/types/',
          '@navigation': './src/navigation/',
          '@styles': './src/styles/',
          '@icons': './src/components/Icon',
        },
        extensions: [
          '.js',
          '.jsx',
          '.ts',
          '.tsx',
          '.json',
          '.png',
          '.jpg',
          '.jpeg',
          '.svg',
        ],
      },
    ],
    'react-native-reanimated/plugin',
  ],
};
