const CALORIE_GOAL = 2000;

enum BiomarkerType {
  TotalCalories = 'Total Calories',
  ActiveEnergyBurned = 'Active Energy',
  ProteinPercentage = 'Protein percentage',
  ProteinGrams = 'Protein grams',
  FatPercentage = 'Fats percentage',
  CarbsPercentage = 'Carbs percentage',

  ActivitySummary = 'ActivitySummary',
  AllergyRecord = 'AllergyRecord',
  AppleExerciseTime = 'AppleExerciseTime',
  AppleStandTime = 'AppleStandTime',
  BasalEnergyBurned = 'Resting Energy',
  BiologicalSex = 'BiologicalSex',
  BloodType = 'BloodType',
  BloodAlcoholContent = 'BloodAlcoholContent',
  BloodGlucose = 'BloodGlucose',
  BloodPressureSystolic = 'Blood Pressure Systolic',
  BloodPressureDiastolic = 'Blood Pressure Diastolic',
  BodyMass = 'BodyMass',
  BodyMassIndex = 'BMI',
  BodyFatPercentage = 'BodyFatPercentage',
  BodyTemperature = 'BodyTemperature',
  DateOfBirth = 'DateOfBirth',
  Biotin = 'Biotin',
  Caffeine = 'Caffeine',
  Calcium = 'Calcium',
  Chloride = 'Chloride',
  Cholesterol = 'Cholesterol',
  ConditionRecord = 'ConditionRecord',
  Copper = 'Copper',
  CoverageRecord = 'CoverageRecord',
  EnergyConsumed = 'EnergyConsumed',
  EnvironmentalAudioExposure = 'EnvironmentalAudioExposure',
  FatMonounsaturated = 'FatMonounsaturated',
  FatPolyunsaturated = 'FatPolyunsaturated',
  FatSaturated = 'FatSaturated',
  Fiber = 'Fiber',
  Folate = 'Folate',
  HeadphoneAudioExposure = 'HeadphoneAudioExposure',
  ImmunizationRecord = 'ImmunizationRecord',
  InsulinDelivery = 'InsulinDelivery',
  Iodine = 'Iodine',
  Iron = 'Iron',
  LabResultRecord = 'LabResultRecord',
  Magnesium = 'Magnesium',
  Manganese = 'Manganese',
  MedicationRecord = 'MedicationRecord',
  Molybdenum = 'Molybdenum',
  Niacin = 'Niacin',
  OxygenSaturation = 'OxygenSaturation',
  PantothenicAcid = 'PantothenicAcid',
  Phosphorus = 'Phosphorus',
  Potassium = 'Potassium',
  ProcedureRecord = 'ProcedureRecord',

  Riboflavin = 'Riboflavin',
  Selenium = 'Selenium',
  Sodium = 'Sodium',
  Sugar = 'Sugar',
  Thiamin = 'Thiamin',
  VitalSignRecord = 'VitalSignRecord',
  VitaminA = 'VitaminA',
  VitaminB12 = 'VitaminB12',
  VitaminB6 = 'VitaminB6',
  VitaminC = 'VitaminC',
  VitaminD = 'VitaminD',
  VitaminE = 'VitaminE',
  VitaminK = 'VitaminK',
  Zinc = 'Zinc',
  Water = 'Water',
  DistanceCycling = 'DistanceCycling',
  DistanceSwimming = 'DistanceSwimming',
  DistanceWalkingRunning = 'DistanceWalkingRunning',
  Electrocardiogram = 'Electrocardiogram',
  FlightsClimbed = 'FlightsClimbed',
  HeartbeatSeries = 'HeartbeatSeries',
  HeartRate = 'HeartRate',
  RestingHeartRate = 'Resting Heart Rate',
  HeartRateVariability = 'HeartRateVariability',
  Height = 'Height',
  LeanBodyMass = 'LeanBodyMass',
  MindfulSession = 'MindfulSession',
  NikeFuel = 'NikeFuel',
  PeakFlow = 'PeakFlow',
  RespiratoryRate = 'RespiratoryRate',
  SleepAnalysis = 'Sleep',
  Steps = 'Steps',
  Vo2Max = 'Vo2Max',
  WaistCircumference = 'WaistCircumference',
  WalkingHeartRateAverage = 'Walking Average Heart Rate',
  Weight = 'Weight',
  Workout = 'Workout',
  WorkoutRoute = 'WorkoutRoute',
  RunningSpeed = 'RunningSpeed',
  RunningPower = 'RunningPower',
  RunningStrideLength = 'RunningStrideLength',
  RunningVerticalOscillation = 'RunningVerticalOscillation',
  RunningGroundContactTime = 'RunningGroundContactTime',
}

enum HealthKitUnit {
  bpm = 'bpm',
  calorie = 'calorie',
  celsius = 'celsius',
  count = 'count',
  day = 'day',
  fahrenheit = 'fahrenheit',
  foot = 'foot',
  gram = 'gram',
  hour = 'hour',
  inch = 'inch',
  joule = 'joule',
  kilocalorie = 'kcal',
  meter = 'meter',
  mgPerdL = 'mgPerdL',
  mile = 'mile',
  minute = 'minute',
  mmhg = 'mmhg',
  literPerMinute = 'literPerMinute',
  mmolPerL = 'mmolPerL',
  percent = 'percent',
  pound = 'pound',
  second = 'second',
}

enum MainBiomarkerType {
  Sleep = 'Sleep',
  Nutrition = 'Nutrition',
  Fitness = 'Fitness',
  Mindfulness = 'Mindfulness',
  Heart = 'Heart',
  Unkown = 'Unknown',
}

export {BiomarkerType, HealthKitUnit, MainBiomarkerType, CALORIE_GOAL};
